a = input('digite algo: ')
print('o tipo primitivo dessee valor é ', type(a))
print('só tem espaços? ', a.isspace())
print('É um numero?', a.isnumeric())
print('È alfabeticp?', a.isalpha())
print('È alfanumerico?', a.isalnum())
print('esta em maiusculas', a.isupper())
print('esta em minusculo?', a.islower())
print('esta capitalizada?', a.istitle())
